# Generated by Django 5.2.11 on 2026-02-23 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20)),
                ('nationality', models.CharField(default='Kenyan', max_length=50)),
                ('marital_status', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=100)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('rent_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.unit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
