# Generated by Django 5.2.11 on 2026-02-24 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_location_property_address_floor_name_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantprofile',
            name='rent_deposit',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='water_deposit',
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='full_name',
            field=models.CharField(default='unknown Tenant', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='id_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='nationality',
            field=models.CharField(blank=True, default='Kenyan', max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenantprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rent_amount_at_signing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='tenants.tenantprofile')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='properties.unit')),
            ],
        ),
    ]
