# Generated by Django 5.2.11 on 2026-02-23 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('purpose', models.CharField(choices=[('verification', 'Account Verification'), ('credentials', 'Account Credentials'), ('billing', 'Monthly Invoice'), ('payment', 'Payment Confirmation'), ('reminder', 'Rent Reminder')], max_length=20)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('status_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
